config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :ducks do
    resources :bookings, only: :create
  end
  resources :bookings, only: [:index, :show, :destroy] do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:edit, :update, :destroy]

  # manage ducks
  get 'profiles/:id/', to: "profiles#show", as: 'profile'
  get 'profiles/:id/new', to: "profiles#new", as: 'profile_duck_new'
  patch 'bookings/:id/accept', to: "bookings#accept", as: 'booking_accepted'
  patch 'bookings/:id/refuse', to: "bookings#refuse", as: 'booking_refused'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/views/profiles/show.html.erb
<div class="container">
  <div class="row">
        <% @user.ducks.each do |duck| %>
         <div class="col-12 col-sm-6 col-lg-4">
          <%= link_to duck_path(duck) do %>

            <div class="card-duck d-flex justify-content-between m-3">

              <!-- CARD IMG & NAME  -->
              <div class="d-flex align-items-center">

                <!-- CARD IMG -->
                <div class="d-flex align-items-center">
                  <%= cl_image_tag(duck.photo, width: 400, height: 300, crop: :fill, class: "avatar" )%>
                </div>

                <!-- CARD NAME -->
                <div class="card-duck-infos">
                    <h2><%= duck.name.capitalize %></h2>
                </div>

              </div>

              <div class="d-flex align-items-center">
                <!-- EDIT BUTTON -->
                <div class="mr-1">
                  <%= link_to edit_duck_path(duck) do %>
                    <%= image_tag "pencil.svg", alt: "alttext", class: "btn-edit" %>
                  <% end %>
                </div>

                <!-- DELETE BUTTON  -->
                <div>
                  <%= link_to duck_path(duck),
                    method: :delete,
                    data: { confirm: "Are you sure?" } do %>
                    <%= image_tag "trash-simple.svg", alt: "alttext", class: "btn-delete" %>
                  <% end %>
                </div>
              </div>

            </div>

          <% end %>

          </div>
        <% end %>
    </div>

</div>