config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :ducks do
    resources :bookings, only: :create
  end
  resources :bookings, only: [:index, :show, :destroy] do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:edit, :update, :destroy]

  # manage ducks
  get 'profiles/:id/', to: "profiles#show", as: 'profile'
  get 'profiles/:id/new', to: "profiles#new", as: 'profile_duck_new'
  patch 'bookings/:id/accept', to: "bookings#accept", as: 'booking_accepted'
  patch 'bookings/:id/refuse', to: "bookings#refuse", as: 'booking_refused'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :duck
  has_many :reviews, dependent: :destroy

  validates :user, presence: true
  validates :duck, presence: true
  validates :start, presence: true
  validates :end, presence: true
  validates :status, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    user = current_user
    @my_bookings = Booking.where(user: user).order(status: :desc)
    @accepted = []
    @refused = []
    @pending = []
    @my_bookings.each do |booking|
      if booking.status == "pending"
        @pending << booking
      elsif booking.status == "accepted"
        @accepted << booking
      else
        @refused << booking
    end
  end
    @my_ducks_bookings = current_user.ducks_bookings
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "accepted"
    @booking.save!
    redirect_to bookings_path
  end

  def refuse
    @booking = Booking.find(params[:id])
    @booking.status = "refused"
    @booking.save!
    redirect_to bookings_path
  end

  def create
    duck = Duck.find(params[:duck_id])
    if duck.bookable?(params[:booking][:start], params[:booking][:end])
      @booking = Booking.new(booking_params)
      @booking.user = current_user
      @booking.status = "pending"
      @booking.duck = duck
      @booking.save!
      redirect_to bookings_path
    else
      redirect_to duck_path(duck), alert: "This duck is already booked"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :duck_id, :start, :end, :status)
  end
end

app/views/bookings/_card.html.erb
  <div class="card-booking">
    <%= cl_image_tag(booking.duck.photo, width: 150, height: 150, crop: :thumb, gravity: :face) %>
    <div class="card-booking-infos">
      <h2><%= booking.duck.name%></h2>
      <p>Owner:
        <%= booking.duck.user.first_name.capitalize %>
        <%= booking.duck.user.last_name.capitalize %></p>
      <p>From
        <%= booking.start%>
        Until
        <%= booking.end%></p>
      <div class=<%= booking.status%>>
        <%= booking.status%>
      </div>
    </div>
  </div>

app/views/bookings/index.html.erb
<div class="container">
  <!-- TABS -->
  <ul class="nav nav-pills justify-content-center p-4 mb-3" id="pills-tab" role="tablist">
    <li class="nav-item">
      <a class="nav-link btn btn-light rounded px-3" id="pills-my-ducks-tab" data-toggle="pill" href="#pills-my-ducks" role="tab" aria-controls="pills-my-ducks" aria-selected="false">confirm</a>
    </li>
    <li class="nav-item">
      <a class="nav-link btn btn-light active rounded px-3" id="pills-pending-tab" data-toggle="pill" href="#pills-pending" role="tab" aria-controls="pills-pending" aria-selected="true">pending</a>
    </li>
    <li class="nav-item">
      <a class="nav-link btn btn-light rounded px-3" id="pills-accepted-tab" data-toggle="pill" href="#pills-accepted" role="tab" aria-controls="pills-accepted" aria-selected="false">accepted</a>
    </li>
    <li class="nav-item">
      <a class="nav-link btn btn-light rounded px-3" id="pills-refused-tab" data-toggle="pill" href="#pills-refused" role="tab" aria-controls="pills-refused" aria-selected="false">refused</a>
    </li>
  </ul>

  <!-- DUCKS TO CONFIRM -->
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade" id="pills-my-ducks" role="tabpanel" aria-labelledby="pills-my-ducks">
      <% @my_ducks_bookings.each do |booking| %>
          <div class="card-booking">
            <%= cl_image_tag(booking.duck.photo,
            width: 150, height: 150, crop: :thumb, gravity: :face) %>
            <div class="card-booking-infos">
              <h2> <%= booking.duck.name %> <%= booking.user.first_name %></h2>
              <p>From <%= booking.start%> Until <%= booking.end%></p>

              <%=link_to booking_accepted_path(booking), method: :patch, class: "checkbox", style: "text-decoration: none;" do %>
                <i class="fas fa-check text-success"></i>
              <% end %>
              <%= link_to booking_refused_path(booking), method: :patch, class: "checkbox" do %>
                <i class="fas fa-times text-danger"></i>
              <% end %>

            </div>
          </div>
      <% end %>
    </div>

    <!-- DUCKS PENDING  -->

    <div class="tab-pane fade show active" id="pills-pending" role="tabpanel" aria-labelledby="pills-pending">
      <%@pending.each do |booking| %>
        <%= link_to booking_path(booking), class: "text-decoration-none" do %>
            <% render "card", booking: booking %>
        <% end %>
      <% end %>
    </div>

    <!-- DUCKS ACCEPTED -->
    <div class="tab-pane fade" id="pills-accepted" role="tabpanel" aria-labelledby="pills-accepted">
      <% @accepted.each do |booking| %>
        <%= link_to booking_path(booking), class: "text-decoration-none" do %>
          <% render "card", booking: booking %>
        <%end%>
      <%end%>
    </div>

    <!-- DUCKS REFUSED -->
    <div class="tab-pane fade" id="pills-refused" role="tabpanel" aria-labelledby="pills-refused">
      <%@refused.each do |booking|%>
        <%= link_to booking_path(booking), class: "text-decoration-none" do %>
          <% render "card", booking: booking %>
        <%end%>
      <%end%>
    </div>
  </div>
  <!--</div>-->
  <br>
</div>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>