config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :ducks do
    resources :bookings, only: :create
  end
  resources :bookings, only: [:index, :show, :destroy] do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:edit, :update, :destroy]

  # manage ducks
  get 'profiles/:id/', to: "profiles#show", as: 'profile'
  get 'profiles/:id/new', to: "profiles#new", as: 'profile_duck_new'
  patch 'bookings/:id/accept', to: "bookings#accept", as: 'booking_accepted'
  patch 'bookings/:id/refuse', to: "bookings#refuse", as: 'booking_refused'
end

app/views/shared/_card.html.erb
<%full_stars = "<i class='fas fa-star'></i>"%>
<%empty_stars = "<i class='far fa-star'></i>"%>
<%half_stars = "<i class='fas fa-star-half-alt'></i>"%>


<% array.each do |duck| %>
  <%= link_to duck_path(duck), class: "text-decoration-none" do %>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('')">
    <%= duck.name %>
    <div class="avatar">
      <%= image_tag(duck.user.photo)%>
    </div>
    <div class="reviews">
      <div class="text-center">
        <%= duck.nb_reviews.to_s + " reviews"%>
      </div>

      <div class="stars">
        <% duck.show_stars[0].times do %>
          <%= full_stars.html_safe %>
        <% end %>
        <% duck.show_stars[1].times do %>
          <%= half_stars.html_safe %>
        <% end %>
        <% duck.show_stars[2].times do %>
          <%= empty_stars.html_safe %>
        <% end %>

      </div>
    </div>
    <div class="city">
      <div>
        <span class="card-price"><%= duck.price.round() %> € / day</span>
      </div>
      <div class="d-flex align-items-end flex-column card-city">
        <div><%= duck.user.city%></div>
      </div>
    </div>


  </div>
  <% end %>

<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_formreview.html.erb
<%= simple_form_for @review do |f| %>
  <%= f.input :content %>
  <%= f.input :stars, collection: (0..5) %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/shared/_navbarhome.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon transparent navbar-light d-flex justify-content-between">
      <!-- LOGO + NAME  -->
      <div class="">
        <div class="navbar-brand d-flex align-items-center">
          <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
            <div><%= image_tag 'duck.png', class: "mx-1" %></div>
            <div>Ducknd</div>
          <% end %>
        </div>
      </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-items-center">
      <li class="nav-item">
        <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        |
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_navbarhome_logged.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon transparent navbar-light d-flex justify-content-between">

  <!-- LOGO + NAME  -->
  <div class="">
    <div class ="navbar-brand d-flex align-items-center">
      <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
        <div><%= image_tag 'duck.png', class: "mx-1" %></div>
        <div>Ducknd</div>
      <% end %>
    </div>
  </div>

  <!-- LINKS  -->
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-items-center">
      <li class="nav-item">
        <%= link_to "Créer une expérience", bookings_path, class: "nav-link" %>
      </li>
       <li class="nav-item">
        |
      </li>
      <li class="nav-item">
        <%= link_to "Manage", profile_path(current_user), class: "nav-link white" %>
      </li>

      <!-- DROPDOWN ON AVATAR -->

      <li class="nav-item dropdown mx-3">
        <%= image_tag user.photo ,
              class: "avatar dropdown-toggle",
              alt: "avatar",
              role: "button",
              data: {
                toggle: "dropdown"
              },
              aria: {
                haspopup: true,
                expanded: false
              }
        %>
        <!-- DROPDOWN MENU -->
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Book a duck",  ducks_path, class: "dropdown-item" %>
          <%= link_to "Add a Duck",  new_duck_path, class: "dropdown-item" %>
          <%= link_to "Manage your ducks",  profile_path(current_user.id), class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Profile",  "#", class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
        </div>

      </li>

    </ul>
  </div>
</div>

app/views/shared/_navbarlogged.html.erb
<% params[:city].present? ? city = params[:city] : city = "" %>
<% params[:start].present? ? start = params[:start] : start = "" %>
<% params[:end].present? ? end_date = params[:end] : end_date = "" %>


<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-green d-flex justify-content-between">

  <div class="d-flex align-items-center">
      <!-- LOGO + NAME  -->
    <div class ="navbar-brand d-flex align-items-center">
      <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
        <div><%= image_tag 'duck.png', class: "mx-1" %></div>
        <div>Ducknd</div>
      <% end %>
    </div>

      <% unless params[:action] == "show" %>
    <!-- FORM -->
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1"><%= image_tag "search.svg", alt: "search" %></span>
        </div>
        <%= simple_form_for "", url: ducks_path, method: :get do |f| %>
        <div class="d-flex align-items-center">
          <div>
            <%= text_field_tag :city,
              params[:query],
              class: "search-field form-control",
              placeholder: "Choose your city",
              value: city
            %>
          </div>
          <div class="">
            <%= f.input :start,
              as: :string,
              required: false,
              label: false,
              placeholder: "From",
              input_html: {
                id: "range_start",
                class: "datepicker ml-2 input-w100px text-center",
                value: start
                } %>
          </div>
          <div>

            <%= f.input :end,
                      as: :string,
                      required: false,
                      label: false,
                      placeholder: "To",
                      input_html: {
                        id: "range_end",
                        class: "datepicker ml-2 input-w100px text-center",
                        value: end_date
                      } %>
          </div>
          <div>
            <%= submit_tag "Search", name: nil, class: "btn btn-primary btn-yellow ml-2" %>
          </div>
        </div>
      <% end %>
      <% end %>

  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-items-center">
      <li class="nav-item">
        <%= link_to "Booking", bookings_path, class: "nav-link" %>
      </li>
       <li class="nav-item">
        |
      </li>
      <li class="nav-item">
        <%= link_to "Manage", profile_path(current_user), class: "nav-link" %>
      </li>
      <li class="nav-item">
        |
      </li>

      <li class="nav-item">
        <%= link_to "Add a Duck",  new_duck_path, class: "nav-link" %>
      </li>

      <!-- DROPDOWN ON AVATAR -->

      <li class="nav-item dropdown mx-3">
        <%= image_tag user.photo ,
              class: "avatar dropdown-toggle",
              alt: "avatar",
              role: "button",
              data: {
                toggle: "dropdown"
              },
              aria: {
                haspopup: true,
                expanded: false
              }
        %>
        <!-- DROPDOWN MENU -->
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Book a duck",  ducks_path, class: "dropdown-item" %>
          <%= link_to "Add a Duck",  new_duck_path, class: "dropdown-item" %>
          <%= link_to "Manage your ducks",  profile_path(current_user.id), class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Profile",  "#", class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
        </div>

      </li>

    </ul>
  </div>
</div>

app/views/shared/_navbarunlogged.html.erb
<% params[:city].present? ? city = params[:city] : city = "" %>
<% params[:start].present? ? start = params[:start] : start = "" %>
<% params[:end].present? ? end_date = params[:end] : end_date = "" %>


<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-green d-flex justify-content-between">

  <div class="d-flex align-items-center">
      <!-- LOGO + NAME  -->
    <div class ="navbar-brand d-flex align-items-center">
      <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
        <div><%= image_tag 'duck.png', class: "mx-1" %></div>
        <div>Ducknd</div>
      <% end %>
    </div>

    <!-- FORM -->
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1"><%= image_tag "search.svg", alt: "search" %></span>
    </div>


      <%= simple_form_for "", url: ducks_path, method: :get do |f| %>
        <div class="d-flex align-items-center">
          <div>
            <%= text_field_tag :city,
              params[:query],
              class: "search-field form-control",
              placeholder: "Choose your city",
              value: city
            %>
          </div>
          <div class="">
            <%= f.input :start,
              as: :string,
              required: false,
              label: false,
              placeholder: "From",
              input_html: {
                id: "range_start",
                class: "datepicker ml-2 input-w100px text-center",
                value: start
                } %>
          </div>
          <div>

            <%= f.input :end,
                      as: :string,
                      required: false,
                      label: false,
                      placeholder: "To",
                      input_html: {
                        id: "range_end",
                        class: "datepicker ml-2 input-w100px text-center",
                        value: end_date
                      } %>
          </div>
          <div>
            <%= submit_tag "Search", name: nil, class: "btn btn-primary btn-yellow ml-2" %>
          </div>
        </div>
      <% end %>

  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto align-items-center">
      <li class="nav-item">
        <%= link_to "Sign in", bookings_path, class: "nav-link" %>
      </li>
       <li class="nav-item">
        |
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", bookings_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>